services:
  status-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: homelab-status-service:latest
    restart: unless-stopped
    environment:
      - TZ=America/Denver
      - DATABASE_URL=sqlite+aiosqlite:////app/data/status.db
      - CHECK_INTERVAL=60
      - TIMEOUT=10
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./frontend:/app/frontend:ro
    networks: [proxy]
    labels:
      - traefik.enable=true
      - traefik.http.routers.status-service.rule=Host(`status.kadenbilyeu.com`) || Host(`status.bikatr7.com`) || Host(`status.kakusui.org`) || Host(`status.easytl.org`) || Host(`status.tetragroup.io`)
      - traefik.http.routers.status-service.entrypoints=web
      - traefik.http.services.status-service.loadbalancer.server.port=8000
      - traefik.http.middlewares.status-cors.headers.accesscontrolallowmethods=GET,POST,PUT,DELETE,OPTIONS
      - traefik.http.middlewares.status-cors.headers.accesscontrolallowheaders=Authorization,Content-Type,X-Requested-With
      - traefik.http.middlewares.status-cors.headers.accesscontrolalloworiginlist=https://kadenbilyeu.com,https://status.kadenbilyeu.com,https://status.bikatr7.com,https://bikatr7.com,https://kakusui.org,https://status.kakusui.org,https://easytl.org,https://status.easytl.org,https://tetragroup.io,https://status.tetragroup.io
      - traefik.http.middlewares.status-cors.headers.accesscontrolallowcredentials=true
      - traefik.http.routers.status-service.middlewares=status-cors@docker

networks:
  proxy:
    external: true
