FROM python:3.11-slim

WORKDIR /app

COPY app/requirements.txt .
COPY app/requirements-dev.txt .
RUN pip install --no-cache-dir -r requirements-dev.txt

COPY app/ .

CMD ["pytest", "-v", "--tb=short"]
